### ISSUE TITLE
Ignoring special ply tags

### ISSUE THREAD

**Issue by LakeIshikawa** [smurn/jPLY#27]
I had some problems loading a .ply file made/edited with CloudCompare.
The header looks like this:

```
ply
format ascii 1.0
comment Author: CloudCompare (TELECOM PARISTECH/EDF R&D)
obj_info Generated by CloudCompare!
```

The problem is that the tag "obj_info" is not supported by the library,
resulting in an `IOException: Unsupported header entry: obj_info`.

The problem is in the following check (PlyReaderFile.java):
```
else if (!line.startsWith("comment ")) {
                throw new IOException("Unsupported header entry: " + line);
            }
```

I'm not sure what is the best way to fix this, probably just raising a warning and ignoring the unkown tag might be safer.

**Comment by raphaelpaiva** [comment]
+1.
This could be easy to implement. Even adding support to this header, as this has nothing to do with the spatial data itself.

**Comment by smurn** [comment]
I agree, ignoring unknown headers is the way to go as it will give the highest degree of compatibility.

Personally, I don't like it if libraries log warnings, especially since there is no standard logging library in java. I'd rather not force anyone to mess with logging configurations just because of jPLY. Also, the ignored headers may contain useful information for someone that knows how to interpret them. 

How about adding a `List<String> getRawHeaders()` function to `PlyReader`? It would contain all the header lines, including the ones we ignored. Those that would like log messages could easily do it themselves. It would also allow access to comments, which might be useful.

If you could send me a pull-request, I'll merge it in.

**Comment by smurn** [comment]
Huhu? `@override` is deprecated? Never heard of that. You got a reference for this?

**Comment by raphaelpaiva** [comment]
Well, there is no depracation note in the docs..

https://docs.oracle.com/javase/8/docs/api/java/lang/Override.html

**Comment by LakeIshikawa** [comment]
I'm sorry that was my fault, I got it completely wrong
